### ISSUE TITLE
In fact, a similar upsampling module was proposed in LiteFlowNet3 (ECCV2020)

### ISSUE THREAD

**Issue by twhui** [coolbeam/UPFlow_pytorch#2]
Do you notice that a similar upsampling module was proposed by another paper - LiteFlowNet3: Resolving Correspondence Ambiguity for More Accurate Optical Flow Estimation in ECCV 2020?

**Comment by coolbeam** [comment]
Thank you for reminding me that. I didn't know this paper before my submission. There is a similar meta-learning operation in LiteFlowNet3. Here the upsampling module is learned in totally unsupervised manner, while the upsampling module in LiteFlowNet3 is learned in a supervised manner.

**Comment by twhui** [comment]
The working mechanism between your proposed upsampling module in UPFlow (CVPR2021) and my proposed upsampling module in LiteFlowNet3 (ECCV2020) is the same. Both of the modules are used for optical flow. I do not think you can ignore my paper simply because your CNN is trained in unsupervised manner instead of supervised manner.

**Comment by coolbeam** [comment]
Hi, I'm sorry for my negligence. We have done our experiments and make presentation to discuss our work before ECCV publication. And we didn't know your work before the submission. 

At this time, I find that the idea of the two module may be similar for using a flow warping operation to address the upsampling issue. But the design and task are different. The unsupervised learning is much difficult than supervised learning because no groundtruth can be used as supervision. In your work, you used feature from I1 to estimate a confidence map, and use groundtruth to learn it. This cannot be done in unsupervised setting. In our work, we warp and compare the two features to find where the bilinear interpolation is erroneous, and no groundtruth is needed to guide this. We attempt to find where the bilinear interpolation is wrong and try to fix it by non-local interpolation source change, not to improve the unconfident flow by local consistency. Other details are also different such as how to produce the guided-flow and how to produce the well interpolated flow result.

Although module in LiteFlowNet3 now can not be directly applied into unsupervised learning setting, I will try my best to add citation and discussion and do experiments to compare the two module in unsupervised setting. Best wishes.

**Comment by coolbeam** [comment]
Hi, I'm sorry for my negligence. We have done our experiments and make presentation to discuss our work before ECCV publication. And we didn't know your work before the submission. 

At this time, I find that the idea of the two module may be similar for using a flow warping operation to address the upsampling issue. But the design and task are different. The unsupervised learning is much difficult than supervised learning because no groundtruth can be used as supervision. In your work, you used feature from I1 to estimate a confidence map, and use groundtruth to learn it. This cannot be done in unsupervised setting. In our work, we warp and compare the two features to find where the bilinear interpolation is erroneous, and no groundtruth is needed to guide this. We attempt to find where the bilinear interpolation is wrong and try to fix it by non-local interpolation source change, not to improve the unconfident flow by local consistency. Other details are also different such as how to produce the guided-flow and how to produce the well interpolated flow result.

Although module in LiteFlowNet3 now can not be directly applied into unsupervised learning setting, I will try my best to add citation and discussion and do experiments to compare the two module in unsupervised setting. Best wishes.

**Comment by twhui** [comment]
In fact, I proposed another version of Flow Field Deformation for ICCV 2019. You may refer to this link (https://github.com/twhui/LiteFlowNet3#Old-Version-of-Flow-Field-Deformation-for-ICCV19-Submission). The confidence map \sigmoid(M) is learned implicitly without using ground-truth. It is basically no different from your design.

**Comment by coolbeam** [comment]
I'm sorry again for my negligence. But you should notice that we also have proposed a flow-warp-flow method in our early version(https://arxiv.org/pdf/2006.16637.pdf), which is submitted to NIPS2020 and AAAI2021. And we uploaded a that version to arXiv in June 2020. We have made a lot of efforts to improve that work and achieved the current results.

**Comment by twhui** [comment]
Please kindly notice that the submission deadline of ICCV2019 was March 2019, while the submission deadline of NIPS2020 was June 2020. I proposed the use of warping to improve optical flow a year earlier than yours. I respect your effort to improve your early research work for CVPR2021. I would like to point out that flow warping is officially presented in LiteFlowNet3, ECCV2020. A preprint is also available at arXiv (https://arxiv.org/pdf/2007.09319.pdf). Hopefully, my clarification is clear.
